### ISSUE TITLE
Run data method before the migration

### ISSUE THREAD

**Issue by erolg** [ka8725/migration_data#17]
Everything seems ok, but

If I want to run data method before migration. How can I do that?

For example, I should remove one column and I need to move all data of the column.

**Comment by ka8725** [comment]
Currently the gem doesn't allow to do this. But actually I think that it make sense to add it. Possible API:

```ruby
class SomeMigration
  def before
    @old_columns = User.pluck(:id, :email)
  end

  def after
    @old_columns.each do |column|
      User.find(column[0]).update_column(:new_email, column[1])
    end
  end

  def change
     # Schema change
  end
end
```

@erolg what do you think is this API good enough?

**Comment by lime** [comment]
The easiest way to do this is to create two migrations, one with only a `data` method and the other with only a `change`.

```
class FirstMigration
  def data
  end
end

class SecondMigration
  def change
  end
end
```

Adding more methods to the API for this sounds a bit like overkill to me. Won't we need corresponding before & after methods both for the data migration and the rollback? It sounds to me like it would get difficult to follow pretty quickly, especially when rolling back.

**Comment by erolg** [comment]
@ka8725 I think API seems quite good.

When rethink with what @lime say, maybe he right.

what do you think? @ka8725 How will you handle rollback migrations?

**Comment by ka8725** [comment]
With rollback things getting to be too complicated with the suggested API. So in order to solve this particular @erolg's case having just 2 migrations as suggested @lime is good enough solution.

**Comment by effect305** [comment]
I would just vote for renaming methods:
data > data_up
rollback > data_down

**Comment by ka8725** [comment]
Done here: https://github.com/ka8725/migration_data/pull/44

**Comment by ka8725** [comment]
Thanks everyone for your input!
