### ISSUE TITLE
Clear schema cache before running #data

### ISSUE THREAD

**Issue by crazyshot** [ka8725/migration_data#26]
So the case is like this:
```ruby
class TestMigration 
  def up
   add_column :users, :newcol, :string
  end
  def data
    User.create(newcol: 'aaa')
  end
end
```
This will probably fail, because 'newcol' might be in ActiveRecord's cache.
I suggest running something like `ActiveRecord::Base.connection.schema_cache.clear!` before #data, although I didn't test it yet, so can't say for sure.

**Comment by ka8725** [comment]
This has been done recently.
