### ISSUE TITLE
shouldn't data migrations run after all schema migrations?

### ISSUE THREAD

**Issue by mfazekas** [ka8725/migration_data#3]
I'm probably missing something important, but shouldn't you run the data migrations after all schema migrations run?
Example, you have an item model, and your write the following migration:
```ruby
class AddFlagToItems < ActiveRecord::Migration
  def change
    add_column :items, :flag, :boolean
  end
  def data
    Item.update_all(flag:true)
  end
end
```
you add your migration test. eg

```ruby
desribe AddFlagToItems do
  describe '#data' do
    it 'works' do
      expect { AddFlagToItems.new.data }.to_not raise_exception
    end
  end
end
```

Later you decide you rename the ```flag``` to ```cool_flag``` with a migrations like:
```ruby
class RenameFlagToCoolFlagInItems < ActiveRecord::Migration
  def change
    rename_column :items, :flag, :cool_flag
  end
end
```

Now your tests on AddFlagToItems.data will fail as there is no more flag on ```item```. If you rewrite the data migration to  ```Item.update_all(cool_flag:true)``` to make test pass then your migration will fail.

A solution would be to make data migrations run after all schema migrations ran.

**Comment by ka8725** [comment]
First of all - you have to write test for the `data` method of any migration. For this purpose the gem provides functionality (look into README). If you write the test correctly it will fail after your new migration. Won't it? After this you will have to fix the test: how to fix it's up to you, but in this case you may move the `Item.update_all(flag:true)` into your new migration and the code will be a little bit differ of course: `Item.update_all(cool_flag:true)`. Or you may also just delete method `data` from the old migration - this solution may be appropriate for you either, I don't know how the field is used in your application and can't decide it. Neither gem can do it.

**Comment by mfazekas** [comment]
I've extended my first comment to show tests one would write. I see 2 issues.
1.) The tests fails, but the migrations is completely fine, there would be no need to change this data migration at all.
2.) The obvious fix is changing ```Item.update_all(flag:true)``` to ```Item.update_all(cool_flag:true)``` which make the tests pass. (But also breaks migrations). 

Fundamentally the tests are running with the latest schema, while the data migrations use the schema in the past.

**Comment by ka8725** [comment]
@mfazekas you are suggesting another idea to solve the problem. The idea requires completely different implementation in code. In you case I suggest you to use some other gem which works for you (I believe there are many implementations on github and you will find something that suites you)  or create new one. But this one works as I explained and will do it further.
