### ISSUE TITLE
rails 5.2 undefined method migrations for ActiveRecord::Migrator for testing

### ISSUE THREAD

**Issue by mbramire** [ka8725/migration_data#35]
in lib/migration_data/testing.rb I had to make a change for rails 5.2

`all_migrations = ActiveRecord::Migrator.migrations(path)`
to
`all_migrations = ActiveRecord::MigrationContext.new(path).migrations`

**Comment by mapreal19** [comment]
@ka8725 maybe we can check rails versions with `Rails::VERSION::MAJOR/MINOR` and have this fixed

**Comment by mapreal19** [comment]
@mbramire https://github.com/ka8725/migration_data/pull/36

Feel free to test this. Will do too when having some time
