### ISSUE TITLE
data method not being executed

### ISSUE THREAD

**Issue by bgvo** [ka8725/migration_data#46]
I tried with both `data` and `data_after`. None of them are being executed.

I'm using Rails 6.1.3.1

This is how the method is defined:

```
class AddOrganizationReferencesToUser < ActiveRecord::Migration[6.1]
  def change
    add_reference :users, :organization, foreign_key: true, type: :ksuid
  end

  def data
    User.all.each do |user|
      org = Organization.create!
      org.users << user
    end
  end
end
```

I suppose there is something in this version of Rails that is causing the data not to be executed?

Thanks!

**Comment by ka8725** [comment]
Hey @bgvo why did you close it? Have you find the way to make it working? Thanks!

**Comment by bgvo** [comment]
Hey! Thanks so much for the quick reply.

Yup. Silly mistake on my behalf. The Gemfile was not saved so gem was not being installed 🤦
