### ISSUE TITLE
Fix typo in example

### ISSUE THREAD

**Issue by dahoo** [ka8725/migration_data#5]
There's a small typo in the testing example:
<pre>des<b>c</b>ribe CreateUsers do</pre>
You could also consider changing `CreateUsers.new.data` to `described_class.new.data` for easier copying.

**Comment by ka8725** [comment]
@dahoo , thanks for the issue. Done: https://github.com/ka8725/migration_data/commit/6d4cd0936f0c5469f833503c863680488beedee8
